Updates to MPElectricsVE and MPInputsVE
BeamMP/BeamMP pull request #123
Opened 2021-05-20 22:28 UTC by jake55520

MPElectricsVE

optimizations
-	removed tostring from localCurrentGear because it would result 
	in it never being equal to data (which is a number), causing
	the loop to run constantly

-	Added loads of unnecessary spammy electrics to the
	disallowed list, thanks to Olrosse for helping me find them
	Should reduce network traffic by a lot with certain vehicles

Improvements
-	Shifting into M mode on a DCT at speed no longer only shifts
	into M1, but checks if it's in 'S' or 'D' mode first then upshifts
	into the according M gear, preventing overrevving
-	Improved and compacted overall gear code for automatic and DCT transmission
-	Added firing rockets support to the ME262 plane
	thanks to Olrosse for finding the trigger
-	DH Super bolide wings sync
-	ESC Mode syncing
-	ABS Mode sync (no more smoke screen from players using arcade ABS)
-	City bus door and suspension level syncing, thanks to 20dka <3
Fixes
-	Fixed typo in trans brake sync

MPInputsVE

-	Fixed inputs getting stuck when no input was present, likely a bodge but it seems to work without any issues
	Switched all inputs back to input events because setting through electrics has a whole load of problems
	like hamster wheel throttle not doing anything, brake lights not working on some cars, the clutch outright not working
	and steering not actuating rear steering
	Changed the filters on the inputs so they're way quicker and more responsive to actual player inputs

2021-05-21 00:43 UTC, 20dka commented on lua/vehicle/extensions/BeamMP/MPElectricsVE.lua
> +					controller.getControllerSafe('doors').setBeamMin({'frontDoors', 'rearDoors'}) -- open doors
you make use of the doorsController var you created instead of calling getControllerSafe again

2021-05-22 11:31 UTC, Starystars67 requested changes
Couple of minor things. Nice work @jake55520

2021-05-22 11:31 UTC, Starystars67 commented on lua/vehicle/extensions/BeamMP/MPElectricsVE.lua
> +		-- Player crouch snycing
spelling mistake :P

2021-05-22 11:31 UTC, Starystars67 commented on lua/vehicle/extensions/BeamMP/MPElectricsVE.lua
> +		-- Bus door syncing
Do doors and controls sync when a user interacts with them now? E.g. when one opens the tailgate of the D-Series does it open for all?

2021-05-22 11:32 UTC, Starystars67 commented
There is also a fair bit of debug printing left in there. Can those be cleaned up to use the log system of the game or removed. Thank you.

2021-05-22 14:37 UTC, jake55520 commented on lua/vehicle/extensions/BeamMP/MPElectricsVE.lua
> +		-- Player crouch snycing
Whoops, and somehow missed the debug prints too, all fixed now :)

2021-05-22 14:37 UTC, jake55520 commented on lua/vehicle/extensions/BeamMP/MPElectricsVE.lua
> +		-- Bus door syncing
afaik that has always worked, but it has to be the owner of the vehicle that's interacting with the tailgate

2021-05-22 15:44 UTC, Starystars67 approved these changes

2021-06-02 21:26 UTC, 20dka approved these changes

2021-06-03 15:47 UTC, merged